### PR TITLE
Feature/protobuff changes for ec

### PR DESCRIPTION
**Pull request by riceluxs1t**
This PR contains enough changes to protobuf message definitions so that EC based file creation is possible.

Changes added by comparing the Hadoop protobuf message definitions and ours. 

Hadoop: https://github.com/riceluxs1t/hadoop/blob/trunk/hadoop-hdfs-project/hadoop-hdfs-client/src/main/proto/ClientNamenodeProtocol.proto

https://github.com/riceluxs1t/hadoop/blob/trunk/hadoop-hdfs-project/hadoop-hdfs-client/src/main/proto/hdfs.proto

RDFS: https://github.com/comp413-2017/RDFS/blob/develop/proto/ClientNamenodeProtocol.proto
https://github.com/comp413-2017/RDFS/blob/develop/proto/hdfs.proto

Note that I expect more changes to the protobuf message definitions as we add more EC capabilities.

### CODE REVIEW

**Comment by riceluxs1t** [comment]
*note* 
1. the branch name is now misleading. It has some changes to file creation.
2. This PR is in progress and is to keep you all updated on what progress I am making and talk about a few potential things to consider as a team.

*What I found*
1. When a file is created, the client first calls the "create" rpc call which creates an empty file, adds blocks individually by calling "addBlock" rpc call, and then finally calls the "complete" rpc call.

2. The create request has an optional field that indicates what ECPolicy to use. Somewhat sure that this "ecPolicyname" field refers to replication / EC (even though it is confusingly named "EC" policy.) HDFS seems to support this functionality of registering a custom EC policy by the user and the EC policy of choice is identified by this string field. My change currently assumes that we only have two default EC policies. replication / EC (i.e. RS). 

*Changes in this code. * (a lot more to follow for EC based file creation to be actually functional)
1. Adds in the FileZNode a field ("replicationForm") that indicates whether the file is stored EC or replication. TODO: whether or not we immediately want to assume that EC means striped and replication means contiguous.

2. Changes here and there that actually set the "replicationForm" field.

3. addBlock is where the bulk of change must occur. We might have to have a separate addBlock helper method that 1) creates a block group 2) creates each storage block this block group consists of and 3) names those pieces using the hierarchical naming scheme. Where I think quick changes should occur is highlighted by TODO comments. Overall, the handlers are very messy and not easy to extend because they assume that replication is the only choice of redundancy form.

**Comment by willkoh** [comment]
I'm just wondering if we should add the todos. Maybe make a PR of the proto changes for now and function definitions, but leave the actual functions to be PR-ed later once they're actually implemented?

**Review by jake-nyquist — APPROVED** [review]

**Review by willkoh — APPROVED** [review]
EC protobuf changes look good!

**Comment by ghost** [comment]
Check out [the lint page](https://github.com/comp413-2017/RDFS/wiki/Lint) for fixing lint errors.

**Comment by LINKIWI** [comment]
@riceluxs1t If you find yourself waiting a really long time just for CI to report lint errors, please see the [wiki page](https://github.com/comp413-2017/RDFS/wiki/Lint) on how you can run the linter locally before pushing.

**Pull request merged**
